### ISSUE TITLE
uint32 guidLow = map->GenerateLowGuid<HighGuid::Pet>();

### ISSUE THREAD

**Issue by zuzanitha** [EmuDevs/Mercenary#15]
In mercenary.cpp error line
uint32 guidLow = map->GenerateLowGuid<HighGuid::Pet>();
in
GenerateLowGuid
and 
Pet>();

**Comment by Easelm** [comment]
Thanks for reporting. I'll update and test soon!

**Comment by Easelm** [comment]
This error doesn't exist in TrinityCore's current revisions. Make sure you have a source at https://github.com/TrinityCore/TrinityCore/commit/dcb7082277447c21b11c4a1d59f105fa342c172e or above.

**Comment by zuzanitha** [comment]
.-. I have trinitycore with elune rev 59..

**Comment by Easelm** [comment]
Okay? What I said still applies. If you have up-to-date source(s) above (as I said) https://github.com/TrinityCore/TrinityCore/commit/dcb7082277447c21b11c4a1d59f105fa342c172e then you wouldn't be getting that error.

You never pasted the actual error that it threw. That would've helped a lot during the investigation progress - but, it still wouldn't have mattered, old sources will always error because this system is up-to-date (not SAYING you are using an old source, just throwing info out there).

**Comment by zuzanitha** [comment]
thanks!
